# Для разработки и прода одновременно.

# Nginx может быть настроен для проксирования запросов к 
# backend-серверу, который работает на другом порту.
# Это позволяет разработчикам работать с фронтендом и бэкендом 
# одновременно, не беспокоясь о проблемах с CORS.


