# Переменные для хостов группы "core".

# Корневая директория приложения на сервере
app_dir: /home/stas/htrBox

# Дректория, где лежит pgdata и его backups на сервере
data_dir: /home/stas/htrBox-data

# Тут лежат чувствительные данные на сервере
secrets_dir: /home/stas/.secrets
