# Переменные для хостов группы "nodes".

# На всех VPS подключаемся как root
ansible_user: root

# Корневая директория приложения на сервере
app_dir: /root/htrBox

# Тут лежат чувствительные данные на сервере
secrets_dir: /root/.secrets

# Порт для VPN соединения
vpn_port: 443
