# ------------------------------------------------------
#  group_vars/nodes.yml
#  Переменные только для хостов группы "nodes".
# ------------------------------------------------------

# На всех VPS подключаемся как root
ansible_user: root
app_dir: /root/htrBox
secrets_dir: /root/.secrets
vpn_port: 443
