all:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/deploy_key
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
    service_domain: stdoq.ru

  children:
    yc:
      hosts:
        yc_main:
          ansible_host: 81.26.176.132
          ansible_user: stas
          app_dir: /home/stas/htrBox
          data_dir: /home/stas/htrBox-data
          secrets_dir: /home/stas/.secrets

    vps:
      vars:
        ansible_user: root
        app_dir: /root/htrBox
        secrets_dir: /root/.secrets
      hosts:
        vps_se:
          ansible_host: 193.25.216.190
          vps_domain: se.stdoq.ru
        vps_nl:
          ansible_host: 151.245.136.168
          vps_domain: nl.stdoq.ru
        vps_ge:
          ansible_host: 2.26.99.243
          vps_domain: ge.stdoq.ru
        vps_pl:
          ansible_host: 2.26.5.104
          vps_domain: pl.stdoq.ru
