[yc]
yc_main ansible_host="{{lookup('env','YC_HOST')}}" ansible_user="{{lookup('env','YC_USER')}}"

[vps]
vps_se ansible_host="{{lookup('env','VPS_HOST_SE')}}" ansible_user=root vps_domain=se.stdoq.ru
vps_nl ansible_host="{{lookup('env','VPS_HOST_NL')}}" ansible_user=root vps_domain=nl.stdoq.ru
vps_ge ansible_host="{{lookup('env','VPS_HOST_GE')}}" ansible_user=root vps_domain=ge.stdoq.ru
vps_pl ansible_host="{{lookup('env','VPS_HOST_PL')}}" ansible_user=root vps_domain=pl.stdoq.ru

[all:vars]
ansible_ssh_private_key_file=~/.ssh/deploy_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
